name: nullgram
description: "nullgram"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: 3.32.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_info_plus: ^12.1.0
  path_provider: ^2.1.5
  qr_flutter: ^4.1.0
  rxdart: ^0.28.0
  logger: ^2.6.2
  flutter_dotenv: ^6.0.0
  share_plus: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
